stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py \raw\train.csv \interim\
    deps:
    - .\data\raw\train.csv
    - .\src\data\make_dataset.py
    params:
    - make_dataset.test_per
    - make_dataset.seed

  traindata_build_features_train:
    cmd: python .\src\features\build_features.py \interim\train_data.csv \processed\
    deps:
    - .\data\interim\
    - .\src\features\build_features.py
    params:
    - build_features.K
    - build_features.seed

  testdata_build_features:
    cmd: python .\src\features\build_features.py \interim\test_data.csv \processed\
    deps:
    - .\data\interim\
    - .\src\features\build_features.py

  train_model:
    cmd: python .\src\models\train_model.py \processed\train_data.csv
    deps:
    - .\data\processed\
    - .\src\models\train_model.py
    params:
    - train_model.model
    - train_model.features
    - train_model.ohe_features
    - train_model.hyperparameters

  visualize:
    cmd: python .\src\visualization\visualize.py \processed\train_data.csv \processed\test_data.csv
      \models\trained_pipeline.pkl
    deps:
    - .\data\processed\
    - .\models\trained_pipeline.pkl
    - .\src\visualization\visualize.py
    outs:
    - dvclive

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/images
