make_dataset:
  test_per: 0.3
  seed: 24

build_features:
  K: 5
  seed: 26

train_model:
  model: RandomForest
  features: ['vendor_id', 'pickup_latitude', 'pickup_longitude', 'dropoff_latitude', 'dropoff_longitude', 
          'pickup_weekday', 'pickup_hour', 'store_and_fwd_flag', 'pickup_cluster_label', 'dropoff_cluster_label'
          ,'trip_distance', 'day_phase', 'trip_duration']
  ohe_features: ['vendor_id','pickup_weekday','day_phase', 'store_and_fwd_flag']
  hyperparameters:
    max_depth: 10
    n_estimators: 20
    



