# .github/workflows/ci_cd.yaml

name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10.8
    - uses: iterative/setup-cml@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run main test
      run: |
        python test.py
        
    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.SECRET_TOKEN }}
        
      run: |
        echo "# Report on Scoring metrics of model" >> report.md
        echo "## Bar Plot" >> report.md
        echo '![](./metrices_bars.png "Bar plot")' >> report.md
        cml comment create report.md
